# Generated by Django 6.0.7 on 2026-07-30 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='product_brand',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='product_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='product_model',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
