# Generated by Django 6.0.7 on 2026-07-31 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_saleitem_product_brand_saleitem_product_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='reserved_stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
