# Generated by Django 6.0.7 on 2026-08-03 18:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_onlineorder_storesettings_onlineorderitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlineorder',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('READY_FOR_PICKUP', 'Ready for Pickup'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_buying_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('new_buying_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('old_selling_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('new_selling_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='shop.product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('INITIAL_STOCK', 'Initial Stock'), ('RESTOCK', 'Stock In (Supplier)'), ('SALE', 'POS Sale'), ('ADJUSTMENT', 'Manual Adjustment'), ('ONLINE_ORDER', 'Online Order Sale'), ('CANCELLED_ORDER', 'Online Order Cancelled')], max_length=20)),
                ('quantity_changed', models.IntegerField(help_text='Positive for additions, negative for deductions')),
                ('unit_cost_at_time', models.DecimalField(decimal_places=2, help_text='Buying price at the time of movement', max_digits=12)),
                ('selling_price_at_time', models.DecimalField(decimal_places=2, default=0, help_text='Selling price at the time of movement', max_digits=12)),
                ('reference', models.CharField(blank=True, help_text='e.g. Sale #TW123 or Invoice #INV456', max_length=200)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='shop.product')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
