# Generated by Django 6.0.7 on 2026-08-09 13:00

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_onlineorder_status_pricehistory_stockmovement'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('color', models.CharField(default='primary', help_text='Bootstrap color: primary, success, danger, warning, info, dark', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_percentage', models.DecimalField(decimal_places=2, help_text='Percentage discount e.g. 10 = 10%', max_digits=5)),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Minimum order to qualify', max_digits=12)),
                ('max_uses', models.PositiveIntegerField(default=0, help_text='0 = unlimited')),
                ('uses_count', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, help_text='Bootstrap icon name e.g. bi-phone', max_length=50),
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/'),
        ),
        migrations.AddField(
            model_name='onlineorder',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='onlineorder',
            name='delivery_zone',
            field=models.CharField(choices=[('kampala', 'Kampala & Environs'), ('upcountry', 'Upcountry / Outside Kampala')], default='kampala', max_length=20),
        ),
        migrations.AddField(
            model_name='onlineorder',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='onlineorder',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='onlineorder',
            name='promo_code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='onlineorder',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('NEW', 'Brand New'), ('USED', 'Used'), ('REFURBISHED', 'Refurbished')], default='NEW', max_length=15),
        ),
        migrations.AddField(
            model_name='product',
            name='estimated_delivery_days',
            field=models.PositiveSmallIntegerField(default=1, help_text='Estimated delivery days for this item'),
        ),
        migrations.AddField(
            model_name='product',
            name='flash_sale_ends',
            field=models.DateTimeField(blank=True, help_text='When the flash sale expires', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='flash_sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Discounted flash sale price (leave blank for no sale)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='source_type',
            field=models.CharField(choices=[('DIRECT', 'In Shop (Direct Stock)'), ('WAREHOUSE', 'Warehouse Stock'), ('SUPPLIER', 'Order from Supplier')], default='DIRECT', max_length=15),
        ),
        migrations.AddField(
            model_name='product',
            name='specifications',
            field=models.TextField(blank=True, help_text='JSON: [{"key": "RAM", "value": "8GB"}, ...]'),
        ),
        migrations.AddField(
            model_name='product',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='warehouse_location',
            field=models.CharField(blank=True, help_text='e.g. Kisekka Market, Kampala', max_length=200),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='delivery_fee_kampala',
            field=models.DecimalField(decimal_places=2, default=Decimal('5000'), help_text='Delivery fee within Kampala (UGX)', max_digits=10),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='delivery_fee_upcountry',
            field=models.DecimalField(decimal_places=2, default=Decimal('15000'), help_text='Delivery fee upcountry/outside Kampala (UGX)', max_digits=10),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='free_delivery_enabled',
            field=models.BooleanField(default=True, help_text='Enable free delivery above the threshold?'),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='free_delivery_threshold',
            field=models.DecimalField(decimal_places=2, default=Decimal('200000'), help_text='Order amount above which delivery is FREE (UGX)', max_digits=12),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='hero_banner_text',
            field=models.CharField(blank=True, default='Quality Electronics & Gadgets — Fast Delivery Across Uganda', max_length=300),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='store_tagline',
            field=models.CharField(blank=True, default='Best Tech Deals in Uganda', max_length=200),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.product')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, to='shop.producttag'),
        ),
    ]
