# Generated by Django 5.2.8 on 2026-08-09 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_producttag_product_condition_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('fee', models.DecimalField(decimal_places=2, default=0, help_text='Delivery fee in UGX', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='onlineorder',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='onlineorder',
            name='customer_address',
            field=models.TextField(help_text='Detailed physical address'),
        ),
        migrations.AddField(
            model_name='onlineorder',
            name='delivery_region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.deliveryregion'),
        ),
    ]
