# Generated by Django 5.2.8 on 2026-08-09 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_deliveryregion_onlineorder_delivery_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesettings',
            name='free_delivery_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='free_delivery_threshold',
            field=models.DecimalField(decimal_places=2, default=200000, max_digits=12),
        ),
        migrations.AddField(
            model_name='storesettings',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='WhatsApp number for customer chat, e.g. 256777XXXXXX', max_length=20),
        ),
    ]
